create table brand_seq (next_val bigint) engine=InnoDB;
insert into brand_seq values ( 1 );
create table calculation_seq (next_val bigint) engine=InnoDB;
insert into calculation_seq values ( 1 );
create table humidifier_component_seq (next_val bigint) engine=InnoDB;
insert into humidifier_component_seq values ( 1 );
create table humidifier_seq (next_val bigint) engine=InnoDB;
insert into humidifier_seq values ( 1 );
create table project_seq (next_val bigint) engine=InnoDB;
insert into project_seq values ( 1 );
create table unit_seq (next_val bigint) engine=InnoDB;
insert into unit_seq values ( 1 );
create table user_seq (next_val bigint) engine=InnoDB;
insert into user_seq values ( 1 );
create table vapor_distributor_seq (next_val bigint) engine=InnoDB;
insert into vapor_distributor_seq values ( 1 );
create table humidifiers_humidifier_components (humidifier_id bigint not null, humidifier_component_id bigint not null);
create table humidifiers_vapor_distributors (humidifier_id bigint not null, vapor_distributor_id bigint not null);
create table tbl_brands (id bigint not null, name varchar(255), primary key (id));
create table tbl_calculations (id bigint not null, date timestamp, project_id bigint, primary key (id));
create table tbl_calculations_unit (calculation_id bigint not null, unit_id bigint not null);
create table tbl_humidifier_components (id bigint not null, article_number varchar(255), optional boolean not null, type varchar(255), brand_id bigint, primary key (id));
create table tbl_humidifiers (id bigint not null, article_number varchar(255), capacity float not null, electric_power float not null, humidifier_type integer, number_of_cylinders integer not null, phase integer not null, price decimal(19,2), type integer, vapor_pipe_diameter integer not null, voltage integer not null, brand_id bigint, primary key (id));
create table tbl_projects (id bigint not null, address varchar(255), title varchar(255), user_id bigint, primary key (id));
create table tbl_units (id bigint not null, type varchar(255), primary key (id));
create table tbl_users (id bigint not null, address_company varchar(255), email varchar(255), full_name varchar(255), name varchar(255), name_company varchar(255), password varchar(255), phone bigint, post varchar(255), role varchar(255), primary key (id));
create table tbl_vapor_distributors (id bigint not null, article_number varchar(255), diameter integer not null, length integer not null, price decimal(19,2), brand_id bigint, primary key (id));
alter table tbl_brands add constraint UK_8g55qmqwsql923gv28vdrwtxq unique (name);
alter table tbl_calculations_unit add constraint UK_rs76n6budrgvm9q9vouka44wd unique (unit_id);
alter table tbl_humidifier_components add constraint UK_tjjj3p4vxslx5xy90h65tw54h unique (article_number);
alter table tbl_humidifiers add constraint UK_o952w0m193aycok6jqpvm87kf unique (article_number);
alter table tbl_vapor_distributors add constraint UK_6j07xe8752ogyudi3rpc484vi unique (article_number);
alter table humidifiers_humidifier_components add constraint FKmplecxea3q9ns7acpr7yrskei foreign key (humidifier_component_id) references tbl_humidifier_components(ID);
alter table humidifiers_humidifier_components add constraint FK9wyisipmmdfew39fi90267mfy foreign key (humidifier_id) references tbl_humidifiers(ID);
alter table humidifiers_vapor_distributors add constraint FKdkhn9p9p2qw6w4shmkaefdb7n foreign key (vapor_distributor_id) references tbl_vapor_distributors(ID);
alter table humidifiers_vapor_distributors add constraint FKg83d4kgpjyitp88a8jhoe393k foreign key (humidifier_id) references tbl_humidifiers(ID);
alter table tbl_calculations add constraint FK1hse8b0equgmqibwa21tqt5rt foreign key (project_id) references tbl_projects(ID);
alter table tbl_calculations_unit add constraint FKco5jcp5un72b6fydgehald7kx foreign key (unit_id) references tbl_units(ID);
alter table tbl_calculations_unit add constraint FK82xi2aw0s82uftw1f574wlmma foreign key (calculation_id) references tbl_calculations(ID);
alter table tbl_humidifier_components add constraint FKavc0ow7w9uq9v6ntr8nm6cefl foreign key (brand_id) references tbl_brands(ID);
alter table tbl_humidifiers add constraint FKcg7ics8isxfem3iow8u8eojc8 foreign key (brand_id) references tbl_brands(ID);
alter table tbl_projects add constraint FKdt49m0dvnk4tbnnitkyq4dyue foreign key (user_id) references tbl_users(ID);
alter table tbl_vapor_distributors add constraint FK5ea6ftdbtykskpbqi6yy42edb foreign key (brand_id) references tbl_brands(ID);
