INSERT INTO humidifier_component (id, article_number, optional, price, type,brand_id,image_id) VALUES (1, 'D107979', 1, 111, 'Вентиляторный распределитель', 1, 10);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (2, 'D107980', 1, 111, 'Вентиляторный распределитель', 1, 10);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (3, 'D69061', 1, 3, 'Панель Master/Slave', 1, 16);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (4, '400502', 1, 4, 'Y переходник', 1, 20);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (5, '930108', 1, 5, 'Датчик протечки', 1, 14);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (6, '300680014', 1, 6, 'Y переходник', 1, 16);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (7, '500600302', 1, 7, 'Шкаф IP55', 1, 9);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (8, 'D110138-1MC', 1, 8, 'Комплект охлаждения дренажа', 1, 12);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (9, 'D110138-2MC', 1, 9, 'Комплект охлаждения дренажа', 1, 12);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (10, 'D110138-3MC', 1, 10, 'Комплект охлаждения дренажа', 1, 12);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (11, 'D110138-LT', 1, 11, 'Комплект охлаждения дренажа', 1, 12);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (12, 'D110143-1LT', 1, 12, 'Шкаф IP55', 1, 9);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (13, 'D110143-1MC', 1, 13, 'Шкаф IP55', 1, 9);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (14, 'D110143-1MT', 1, 14, 'Шкаф IP55', 1, 9);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (15, 'D110143-1SC', 1, 15, 'Шкаф IP55', 1, 9);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (16, 'D110143-2LT', 1, 16, 'Шкаф IP55', 1, 9);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (17, 'D110143-2MC', 1, 17, 'Шкаф IP55', 1, 9);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (18, 'D110143-3MC', 1, 18, 'Шкаф IP55', 1, 9);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (19, 'D110193', 1, 19, 'Трубка для подачи пара армированная синтетической нитью d=25 мм (цена за метр)', 1, 19);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (20, 'D110198-1-DCC-SP', 1, 20, 'Разборн. Цилиндр', 1, 5);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (21, 'D110199-2-CC-SP', 1, 21, 'Разборн. Цилиндр', 1, 5);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (22, 'D110313', 1, 22, 'ЖК дисплей', 1, 15);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (23, 'D110325', 1, 23, 'Кабель для ЖК дисплея [10м max]', 1, 2);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (24, 'D113110-1LT', 1, 24, 'Рама для напольного монтажа', 1, 11);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (25, 'D113110-1MC', 1, 25, 'Рама для напольного монтажа', 1, 11);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (26, 'D113110-1SC', 1, 26, 'Рама для напольного монтажа', 1, 11);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (27, 'D113110-2LT', 1, 27, 'Рама для напольного монтажа', 1, 11);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (28, 'D113110-2MC', 1, 28, 'Рама для напольного монтажа', 1, 11);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (29, 'D113110-3MC', 1, 29, 'Рама для напольного монтажа', 1, 11);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (30, 'D113226-25-40-SP', 1, 30, 'Переходник Ø40/25 мм', 1, 1);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (31, 'D113226-40-60-SP', 1, 31, 'Переходник Ø60/40 мм', 1, 1);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (32, 'D113226-50-60', 1, 32, 'Переходник Ø60/55 мм', 1, 1);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (33, 'D113312', 1, 33, 'Трубка для отвода конденсата для канальных парораспределителей, d = 8мм (Цена за метр)', 1, 4);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (34, 'D113314-25', 1, 34, 'Система подогрева воды в цилиндре [+65°C]', 1, 13);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (35, 'D113314-40', 1, 35, 'Система подогрева воды в цилиндре [+65°C]', 1, 13);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (36, 'D113321', 1, 36, 'Комнатный датчик влажности (с дисплеем)', 1, 17);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (37, 'D113322', 0, 37, 'Трубка для подачи пара армированная синтетической нитью d=60 мм (цена за метр)', 1, 19);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (38, 'D116650', 0, 38, 'Трубка для отвода конденсата для канальных парораспределителей, d = 13мм (Цена за метр)', 1, 4);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (39, 'D116711', 1, 39, 'Кожух цилиндра', 1, 3);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (40, 'D128015-1LT', 0, 40, 'Трубки для подачи(0,5 м ,с фитингом 3/4”)  и слива воды(1м,Ø=60мм)', 1, 21);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (41, 'D128015-1MC', 0, 41, 'Трубки для подачи(0,5 м ,с фитингом 3/4”)  и слива воды(1м,Ø=60мм)', 1, 21);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (42, 'D128015-2MC', 0, 42, 'Трубки для подачи(0,5 м ,с фитингом 3/4”)  и слива воды(1м,Ø=60мм)', 1, 21);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (43, 'D128015-3MC', 0, 43, 'Трубки для подачи(0,5 м ,с фитингом 3/4”)  и слива воды(1м,Ø=60мм)', 1, 21);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (44, 'D83499', 1, 44, 'Комнатный датчик влажности (настенный)', 1, 18);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (45, 'D83502', 1, 45, 'Канальный датчик', 1, 8);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (46, 'D83503', 1, 46, 'Канальный ограничительный гигростат', 1, 7);
INSERT INTO humidifier_component (id, article_number, optional, price, type ,brand_id,image_id) VALUES (47, 'D95524', 1, 47, 'Трубка для подачи пара армированная синтетической нитью d=40 мм (цена за метр)', 1, 19);