package ru.systemairac.calculator.myEnum;

public enum HumidifierComponentType {
    CYLINDER_CASING,
    CYLINDER_WATER_HEATING_KIT,
    DRAINAGE_COOLING_KIT,
    FAN_DISTRIBUTOR,
    LEAK_SENSOR,
    LED_DISPLAY,
    MASTER_SLAVE_PANEL,
    OTHER_DIAMETER_ADAPTER,
    PROTECTIVE_CABINET,
    ROOM_HUMIDITY_SENSOR,
    Y_ADAPTER
}
